//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clanarina> Clanarinas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<NaruceniSuplement> NaruceniSuplements { get; set; }
        public virtual DbSet<NovacKorisnika> NovacKorisnikas { get; set; }
        public virtual DbSet<Smjena> Smjenas { get; set; }
        public virtual DbSet<SmjenaKorisnika> SmjenaKorisnikas { get; set; }
        public virtual DbSet<Suplement> Suplements { get; set; }
        public virtual DbSet<Termin> Termins { get; set; }
        public virtual DbSet<Trening> Trenings { get; set; }
        public virtual DbSet<UlogaUTeretani> UlogaUTeretanis { get; set; }
        public virtual DbSet<VrstaClanarine> VrstaClanarines { get; set; }
        public virtual DbSet<VrstaVjezbe> VrstaVjezbes { get; set; }
    }
}
