//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervacijaTreninga
    {
        public int trening_id { get; set; }
        public string korisnik_korisnickoIme { get; set; }
        public System.DateTime vrijemeRezervacije { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Trening Trening { get; set; }
    }
}
