//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smjena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smjena()
        {
            this.SmjenaZaposlenikas = new HashSet<SmjenaZaposlenika>();
        }
    
        public int ID { get; set; }
        public string naziv { get; set; }
        public Nullable<System.TimeSpan> od { get; set; }
        public Nullable<System.TimeSpan> @do { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmjenaZaposlenika> SmjenaZaposlenikas { get; set; }
    }
}
