//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmjenaKorisnika
    {
        public int smjena_id { get; set; }
        public string zaposlenik_korisnickoIme { get; set; }
        public System.TimeSpan od { get; set; }
        public System.TimeSpan @do { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Smjena Smjena { get; set; }
    }
}
